### ISSUE TITLE
コメント

### ISSUE THREAD

**Issue by c0b210990e** [c0b21043/ProjExD#15]
https://github.com/c0b21043/ProjExD/blob/c69fe8298336bbe4e0829250c58c10d2c90fea94/ex05/fight_koukaton.py#L57

クラス名についてのコメントがあって良いと思いました。
関数名にもコメントがあるとより見やすくなると思いました。

**Comment by c0b21043** [comment]
ありがとうございます。関数のところにもコメントを追加しました。
