### ISSUE TITLE
参考になりました

### ISSUE THREAD

**Issue by a123ktx** [c0b21043/ProjExD#16]
https://github.com/c0b21043/ProjExD/blob/c69fe8298336bbe4e0829250c58c10d2c90fea94/ex05/fight_koukaton.py#L188
自分もこうかとんが爆弾に当たった後に色を変える処理をしようとしたのですが、やり方を思いつきませんでした
今後の参考にするために、コメントで説明を付けてもらえませんか？

**Comment by c0b21043** [comment]
ありがとうございます。Tackleクラスのところに説明を追加しました。
