### ISSUE TITLE
リストの表記について

### ISSUE THREAD

**Issue by c0b21145** [c0b21043/ProjExD#6]
https://github.com/c0b21043/ProjExD/blob/6b6ab93e5935f1a66b1ae219bddb27632e3ceccb/ex03/maze.py#L68

photos = [tk.PhotoImage(file=f'fig/{i}.png') for i in range(1,10)]
の様に書くと短くなるので良ければ使ってみてください

**Comment by c0b21043** [comment]
ありがとうございます。コード参考にさせていただきました。修正しました。
